#!/bin/bash

echo "================================================"
echo "Browser Testing Guide"
echo "================================================"
echo ""
echo "1. Open: http://localhost:3001"
echo "   Expected: See login form"
echo ""
echo "2. Click Login and enter:"
echo "   Email: suhani@stage.in"
echo "   Password: 123456"
echo ""
echo "3. After login, check:"
echo "   ✓ URL should change to /dashboard"
echo "   ✓ Should see sidebar with navigation"
echo "   ✓ Should see header with 'Welcome back, Suhani!'"
echo "   ✓ Should see stats cards"
echo ""
echo "4. If you see blank page:"
echo "   a. Press F12 (open Developer Tools)"
echo "   b. Click 'Console' tab"
echo "   c. Look for RED errors"
echo "   d. Share the error messages"
echo ""
echo "5. Debug page: http://localhost:3001/debug"
echo "   This shows authentication state and API status"
echo ""
echo "================================================"
echo "Services Running:"
echo "================================================"
echo ""
curl -s http://localhost:3000/health | grep -q "ok" && echo "✓ Backend: http://localhost:3000" || echo "✗ Backend: NOT RUNNING"
curl -s -o /dev/null -w "%{http_code}" http://localhost:3001 | grep -q "200" && echo "✓ Frontend: http://localhost:3001" || echo "✗ Frontend: NOT RUNNING"
echo ""
