'use client';

import { useState, useEffect, useRef } from 'react';
import { Sparkles, Loader2, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Card, CardContent } from '@/components/ui/card';
import { postsApi, CaptionVariation } from '@/lib/api/posts';
import { Language, Platform } from '@/lib/types/api';
import { cn } from '@/lib/utils';

interface CaptionGeneratorProps {
  videoTitle: string;
  platform: Platform;
  selectedCaption: CaptionVariation | null;
  onSelect: (caption: CaptionVariation) => void;
  onLanguageChange: (language: Language) => void;
  language: Language;
}

const languageOptions = [
  { value: 'ENGLISH' as Language, label: 'English' },
  { value: 'HINGLISH' as Language, label: 'Hinglish' },
  { value: 'HARYANVI' as Language, label: 'Haryanvi' },
  { value: 'HINDI' as Language, label: 'Hindi' },
  { value: 'RAJASTHANI' as Language, label: 'Rajasthani' },
  { value: 'BHOJPURI' as Language, label: 'Bhojpuri' },
];

export function CaptionGenerator({
  videoTitle,
  platform,
  selectedCaption,
  onSelect,
  onLanguageChange,
  language,
}: CaptionGeneratorProps) {
  const [variations, setVariations] = useState<CaptionVariation[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const hasAutoGenerated = useRef(false);

  // Auto-generate captions when component mounts (video selected)
  useEffect(() => {
    if (videoTitle && !hasAutoGenerated.current && variations.length === 0) {
      hasAutoGenerated.current = true;
      handleGenerate();
    }
  }, [videoTitle]);

  const handleGenerate = async () => {
    setIsGenerating(true);
    setError(null);

    try {
      const response = await postsApi.generateCaption({
        videoTitle,
        language,
        platform,
      });
      setVariations(response.variations);

      // Auto-select first variation
      if (response.variations.length > 0) {
        onSelect(response.variations[0]);
      }
    } catch (err: any) {
      setError(err.response?.data?.message || 'Failed to generate captions. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="space-y-4">
      <div>
        <h3 className="text-lg font-semibold text-white mb-1">AI Caption Generator</h3>
        <p className="text-sm text-neutral-500 mb-4">
          Powered by Claude AI — generating engaging captions in your language
        </p>
      </div>

      {/* Language Selector */}
      <div className="space-y-2">
        <Label htmlFor="language" className="text-neutral-400 text-xs">
          Language
        </Label>
        <div className="flex gap-2">
          <Select
            value={language}
            onValueChange={(value) => {
              onLanguageChange(value as Language);
            }}
          >
            <SelectTrigger className="flex-1 bg-[#0a0a0a] border-[#1a1a1a] text-white">
              <SelectValue placeholder="Select language" />
            </SelectTrigger>
            <SelectContent>
              {languageOptions.map((option) => (
                <SelectItem key={option.value} value={option.value}>
                  {option.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Button
            onClick={handleGenerate}
            disabled={isGenerating}
            className="flex-shrink-0 bg-red-600 hover:bg-red-700 text-white"
          >
            {isGenerating ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Generating...
              </>
            ) : variations.length > 0 ? (
              <>
                <RefreshCw className="mr-2 h-4 w-4" />
                Regenerate
              </>
            ) : (
              <>
                <Sparkles className="mr-2 h-4 w-4" />
                Generate
              </>
            )}
          </Button>
        </div>
      </div>

      {/* Error Message */}
      {error && (
        <div className="rounded-md bg-red-500/10 border border-red-500/20 p-3 text-sm text-red-400">
          {error}
        </div>
      )}

      {/* Caption Variations */}
      {variations.length > 0 && (
        <div className="space-y-3">
          <Label className="text-neutral-400 text-xs">Select a caption variation</Label>
          <div className="space-y-3 max-h-[400px] overflow-y-auto">
            {variations.map((variation, index) => (
              <Card
                key={index}
                className={cn(
                  'cursor-pointer transition-all border-[#1a1a1a] bg-[#0a0a0a] hover:border-red-500/50',
                  selectedCaption?.caption === variation.caption && 'border-red-500 bg-red-500/5'
                )}
                onClick={() => onSelect(variation)}
              >
                <CardContent className="p-4">
                  <div className="flex items-start gap-3">
                    <div
                      className={cn(
                        'mt-1 flex h-5 w-5 flex-shrink-0 items-center justify-center rounded-full border-2',
                        selectedCaption?.caption === variation.caption
                          ? 'border-red-500 bg-red-500'
                          : 'border-neutral-600'
                      )}
                    >
                      {selectedCaption?.caption === variation.caption && (
                        <div className="h-2 w-2 rounded-full bg-white"></div>
                      )}
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm whitespace-pre-wrap text-neutral-200">
                        {variation.caption}
                      </p>
                      {variation.hashtags.length > 0 && (
                        <div className="mt-2 flex flex-wrap gap-2">
                          {variation.hashtags.map((tag, tagIndex) => (
                            <span key={tagIndex} className="text-xs text-red-500 font-medium">
                              {tag}
                            </span>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      )}

      {/* Generating State */}
      {isGenerating && variations.length === 0 && (
        <div className="rounded-lg border border-[#1a1a1a] bg-[#0a0a0a] p-8 text-center">
          <Sparkles className="mx-auto h-12 w-12 text-red-500 animate-pulse mb-4" />
          <h4 className="font-semibold text-white mb-2">AI is writing your captions...</h4>
          <p className="text-sm text-neutral-500">
            Claude AI is generating 3 unique caption variations
          </p>
        </div>
      )}
    </div>
  );
}
